name: Deploy to AWS (Landpage)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build application
        run: |
          npm run build

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: sa-east-1
          S3_BUCKET_NAME: mamao-landpage-tashiro
          CF_DISTRIBUTION_ID: EE7HOT45Y65FF
        run: |
          aws s3 sync build/ s3://${S3_BUCKET_NAME}/ --delete
          aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
